image: fedora

sync:

  script:
    - echo "Synchronizing $CI_COMMIT_BRANCH branch from $UPSTREAM_URL to $CI_PROJECT_URL"
    - dnf install -y git
    - git remote set-url origin https://sync:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git remote remove upstream || true
    - git remote add upstream $UPSTREAM_URL || true
    - git remote -v
    - git fetch upstream $CI_COMMIT_BRANCH
    - git checkout upstream/$CI_COMMIT_BRANCH
    - git log -1
    - GIT_SSL_NO_VERIFY=true git push origin HEAD:$CI_COMMIT_BRANCH

  rules:
    - if: $SYNC == "true"

  tags:
    # Use shared runners.
    - shared
